### ISSUE TITLE
[BUG] iOS - Credit card payment process crashes when trying to execute "creditCardPayment"

### ISSUE THREAD

**Issue by oriana-94** [Ingenico-ePayments/connect-sdk-client-swift#8]
"Fatal error: Unexpectedly found nil while unwrapping an Optional value
IngenicoConnectKit/AssetManager.swift:162: Fatal error: Unexpectedly found nil while unwrapping an Optional value
flutter: PaymentOption: {label: Cards, id: cards, logoUrl:
templates/master/global/css/img/ppimages/group-card.png, displayOrder:
0, isAccount: false}
* thread #35, queue = 'com.apple.root.default-qos', stop reason = Fatal
error: Unexpectedly found nil while unwrapping an Optional value
     frame #0: 0x000000018609aebc
libswiftCore.dylib`_swift_runtime_on_report
libswiftCore.dylib`_swift_runtime_on_report:
->  0x18609aebc <+0>: ret
libswiftCore.dylib`_swift_reportToDebugger:
     0x18609aec0 <+0>: b      0x18609aebc               ;
_swift_runtime_on_report
libswiftCore.dylib`_swift_shouldReportFatalErrorsToDebugger:
     0x18609aec4 <+0>: adrp   x8, 463394
     0x18609aec8 <+4>: ldrb   w0, [x8, #0x60c]
Target 0: (Runner)
  stopped.
Lost connection to device."

Tested on iOS 15.4.1, on iPhone X, iPhone 12 and iPhone 8. This error happens everytime.

Hotfix is placing a "return" at the very start of each of the two "updateImages"-functions in the AssetManager.swift. (I also commented out the whole code in both "updateImages"-functions just to be safe.

**Comment by LeonStemerdink-Worldline** [comment]
Hello Matthias,
Thank you for reporting this issue. 
We are working on a fix and we will have a release ready as soon as possible.

**Comment by LeonStemerdink-Worldline** [comment]
This issue has been fixed in release 5.6.0.

**Comment by rikvanthof** [comment]
Closed
